name: mekfire
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0
resolution: workspace

scripts:
  # To generate library barrel file: https://pub.dev/packages/index_generator
  generate-library: >-
    dart pub global activate index_generator 4.0.0 &&
    dart pub global run index_generator

  # Integration tools
  integration: dart pub global run rps check-format && dart pub global run rps analyze
  check-format: >-
    dart format --line-length 100 --set-exit-if-changed --output none
    $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")
  analyze: flutter analyze --no-fatal-infos

dependencies:
  flutter: { sdk: flutter }

  firebase_auth: ^5.3.3

  rxdart: ^0.28.0

  flutter_riverpod: ^2.6.1
  reactive_forms: ^17.0.1
  mek: { path: ../mek_framework }
  mekart: { path: ../mekart }

dev_dependencies:
  mek_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

index_generator:
  exclude:
    - '**.g.dart'
    - '{_,**/_}*.dart'
  libraries:
    - directory_path: lib