name: mekart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  web: '>=0.5.0 <2.0.0'
  meta: ^1.12.0
  fast_immutable_collections: ^10.2.0
  synchronized: ^3.1.0

  collection: ^1.18.0

dev_dependencies:
  mek_lints: ^4.0.0
