name: mekart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

scripts:
  bootstrap: dart pub global activate rps 0.7.0

  # To generate library file: https://pub.dev/packages/index_generator
  generate-library: >-
    dart pub global activate index_generator 4.0.0 &&
    dart pub global run index_generator

  # Integration tools
  integration: dart pub global run rps check-format && dart pub global run rps analyze
  check-format: >-
    dart format --line-length 100 --set-exit-if-changed --output none
    $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")
  analyze: dart analyze

dependencies:
  web: '>=0.5.0 <2.0.0'
  meta: ^1.12.0
  fast_immutable_collections: ^11.0.4
  synchronized: ^3.3.1
  logging: ^1.3.0
  decimal: ^3.0.2
  collection: ^1.18.0

dev_dependencies:
  mek_lints: ^4.0.0

index_generator:
  exclude:
    - '**.g.dart'
    - '{_,**/_}*.dart'
  libraries:
    - directory_path: lib
      exclude: [ '*.dart', '**/cli_**' ]
