name: mekcli
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.4.4

scripts:
  bootstrap: dart pub global activate rps 0.7.0

  # To generate library file: https://pub.dev/packages/index_generator
  generate:library: >-
    dart pub global activate index_generator 3.4.1 &&
    dart pub global run index_generator

  # Integration tools
  integration: dart pub global run rps check-format && dart pub global run rps analyze
  check-format: >-
    dart format --line-length 100 --set-exit-if-changed --output none
    $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")
  analyze: dart analyze

dependencies:
#  meta: ^1.12.0
#  fast_immutable_collections: ^10.2.2
#  synchronized: ^3.1.0
  logging: ^1.3.0
  collection: ^1.18.0
  uuid: ^4.5.1
  mekart: { path: ../mekart }

dev_dependencies:
  mek_lints: ^4.0.0

index_generator:
  exclude:
    - '**.g.dart'
    - '{_,**/_}*.dart'
  indexes:
    - path: lib
