name: rds
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <3.4.0'

scripts:
  activate: dart pub global activate --source=path .

  # Integration tools
  integration: rps check-format && rps analyze
  check-format: >-
    dart format --line-length 100 --set-exit-if-changed --output none
    $(find . ! -path "./.dart_tool/**" ! -path "./build/**" -name "*.dart" ! -name "*.g.dart")
  analyze: dart analyze

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  characters: ^1.3.0
  glob: ^2.1.2
  path: ^1.9.0
  pool: ^1.5.1
  io: ^1.0.4

dev_dependencies:
  mek_lints: ^3.0.0

executables:
  rds:
