name: mek_framework integration

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: mek_framework

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.x
      - name: Resolve dependencies
        run: flutter pub get
        timeout-minutes: 2

      - name: Activate rps package
        run: dart pub global activate rps

      - name: Check code formatting
        run: dart pub global run rps check-format
      - name: Analyze code
        run: dart pub global run rps analyze
      - name: Test code
        run: dart pub global run rps test
